In [ ]:
import pandas as pd
import seaborn as sns
import xlwings as xw

df = sns.load_dataset('titanic')
print(f"{df.shape = }")
print(df.head().to_string())

df.shape = (891, 15)
   survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True

In [ ]:
import xlwings as xw

wb = xw.Book()
ws = wb.sheets.add('df')
ws["A1"].value = df
ws.tables.add(source=ws["A1"].expand())

 ## read df
 ####################################################################################################

In [ ]:
ws["A1"].expand()

In [ ]:
df2 = ws["A1"].expand().options(pd.DataFrame).value
df2

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
Column1,,,,,,,,,,,,,,,
0.0,0.0,3.0,male,22.0,1.0,0.0,7.2500,S,Third,man,True,None,Southampton,no,False
1.0,1.0,1.0,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2.0,1.0,3.0,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,None,Southampton,yes,True
3.0,1.0,1.0,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False
4.0,0.0,3.0,male,35.0,0.0,0.0,8.0500,S,Third,man,True,None,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886.0,0.0,2.0,male,27.0,0.0,0.0,13.0000,S,Second,man,True,None,Southampton,no,True
887.0,1.0,1.0,female,19.0,0.0,0.0,30.0000,S,First,woman,False,B,Southampton,yes,True
888.0,0.0,3.0,female,NaN,1.0,2.0,23.4500,S,Third,woman,False,None,Southampton,no,False
889.0,1.0,1.0,male,26.0,0.0,0.0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890.0,0.0,3.0,male,32.0,0.0,0.0,7.7500,Q,Third,man,True,None,Queenstown,no,True

In [ ]:
df2 = ws["A1"].expand().options(pd.DataFrame,index=False).value
df2

,Column1,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0.0,0.0,3.0,male,22.0,1.0,0.0,7.2500,S,Third,man,True,None,Southampton,no,False
1,1.0,1.0,1.0,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2.0,1.0,3.0,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,None,Southampton,yes,True
3,3.0,1.0,1.0,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4.0,0.0,3.0,male,35.0,0.0,0.0,8.0500,S,Third,man,True,None,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886.0,0.0,2.0,male,27.0,0.0,0.0,13.0000,S,Second,man,True,None,Southampton,no,True
887,887.0,1.0,1.0,female,19.0,0.0,0.0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,888.0,0.0,3.0,female,NaN,1.0,2.0,23.4500,S,Third,woman,False,None,Southampton,no,False
889,889.0,1.0,1.0,male,26.0,0.0,0.0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,890.0,0.0,3.0,male,32.0,0.0,0.0,7.7500,Q,Third,man,True,None,Queenstown,no,True

In [ ]:
wb.app.quit()